# statement of teaching and training philosophy

## Teaching Philosophy

<!-- must provide evidence for excellence in, and commitment to, undergraduate teaching;  -->
<!-- must provide evidence for potential for creating innovative instructional environments.  -->

<!-- I imagine this section to be on how I go about teaching -->

My philosophy on teaching can best be broken down into four categories: __appropriate course structure__, __responsive teaching__, __motivation__, and __self-improvement__.

### Appropriate Structure

You and I don't really know English. We only know enough for it to be a sufficiently useful tool for our own daily activities. I take this concept to heart as I design and deliver my courses. It's fallacious to design a course around _topics_, but rather on building _skills_ for a certain purpose. To me, these skills formulated as a list of __learning objectives__ (LO's) act as a "true north" that all components of a course point towards, and are the most important structure to the course. For example, course content on the topic "heteroskedasticity" could be developed in many directions. The students, thinking they have to "know heteroskedasticity", get stuck studying its never-ending scope. Instead, a learning objective such as "modify a linear model to appropriately incorporate heteroskedasticity based on data diagnostics" provides direction for the teaching team to create material, and clarity for the students. For concrete examples, take a look at [the DSCI 551 notes](https://ubc-mds.github.io/DSCI_551_stat-prob-dsci/lectures/), or my other course materials.

Clarity about the course structure and expectations is important for equipping students with a map of what they need to do to succeed. In addition to discussing how students should use the LO's, describing the summative assessments and a course syllabus is also important, as well as making it easy to navigate course material (see, for example, the [STAT 545A/547M syllabus website](https://stat545.stat.ubc.ca/)). Informing the students of any changes or of any mistakes, no matter how painful, is also critical for maintaining clarity.

### Responsive teaching

Too much structure can stymie a course. This is because, while preparing course material, the instructor is not truly equipped with the clarity of how to most appropriately deliver material until the material has been delivered. For example, a question for the class might have seemed insightful when it was being prepared, but maybe during class the question doesn't end up being insightful. Or, maybe the lecture delivery time was underestimated. The answer to addressing this issue is responsive teaching.

Responsive teaching to me is about staying in touch with the class to get a feel for areas that need more or less attention. For example, it means: taking a break when the energy of the class is low; responding to class confusion by explaining something in a different way on the whiteboard; or spending more or less time on something after realizing its importance mid-class. In this way, teaching is more akin to improv comedy, where actors must respond to random cues from the audience (I've taken lessons). I believe in embracing a mindset of letting go and trusting in yourself to respond appropriately the moment things go off course, and to also be humble and admit when you don't know something. This type of spontaneity sometimes also requires realizing and appropriately acting on your agency in adapting a course on the fly. Understanding that a course is flexible allows you to be nimble during contact hours with students, as opposed to feeling stuck in delivering the course exactly as it was originally laid out. However, it's important to be strategic when making changes so that things remain orderly and as seemless as possible for the students, and to be clear about any changes made. I like using the start of class to check in and return to a roadmap of the course so that everyone remains on board a moving bus.

Contact time with students is critical for adapting my teaching to the students, and provides tremendous value for students to actually enrol in a program as opposed to taking an online course. Perhaps the most effective method for doing this is making a point to engage with each student in lab. Equally as powerful are discussion-style office hours. I no longer hold my office hours in my office, because the office hour model whereby students just drop by to ask a question is just not effective. There ends up being a queue of students, usually asking common questions, and these students feel pressured to leave the office so that others can get a turn. Instead, I hold my office hours in a lab-like room suitable for collaboration. I end up leading a whole-group discussion prompted by student questions. This gives me even more insight as to how things are going in class, and allows me the opportunity to modify the course moving forward or make clarifications.

Some other methods for connecting with the students are:

- being present on the course Slack channel (and sometimes even other course channels) to provide more insight,
- sending out a 1-minute long early survey about how the course is going,
- taking the time to talk to students who approach me during the mid-class break or after class,
- pausing to ask questions and check for insight in the classroom,
- applying active learning strategies such as think-pair-share or live coding, and
- checking in to see how things are going at the start of each class, by asking questions like "how are we feeling about the quiz coming up next week", or "how are we feeling this week".

### Motivation

Neither structure nor responsive teaching will suffice if the students don't know the reason for discussing the course material.

I take to heart what I learned from Greg Wilson, that teaching is much more about motivating students than it is knowledge transfer. Students have access to any information they want through the internet, but a classroom environment has the powerful advantage of the presence of peers and an engaging instructor. On the teaching front, this means being enthusiastic, and focussing on why they should care about the things I talk about. It also means being aware of the lengthy (usually 80-minute) time frame that students are present for (and that's just for one class), by taking a break mid-class, returning to the big-picture, and providing additional instructions for exercises for people who may have "fallen off the bus". I'm pleased that I regularly receive ample praise on my instructor evaluations, and I encourage you to take a look.

### Self-Improvement

What's better than effective teaching? Teaching that continually becomes more effective.

Community engagement is one method to become a better teacher. This means keeping an open dialogue and sharing experiences with other teachers, especially my colleagues. Aside from simple acts like sharing ideas and experiences through Slack and gatherings, I'm proud that my team gives and receives formative feedback on our teaching by visiting each others' lectures.

An after-action review is another effective method, involving capturing the insight you gain after teaching. There are three ways I engage in an after-action review. First, I capture regular insight throughout the delivery of the course as GitHub Issues, so that the insight can easily be referred to in the future and by any of my colleagues. Secondly, I find keeping a teaching journal that's not tied to a specific course is useful for becoming a better teacher in general -- and it's even easier now that my team has our lectures recorded. Thirdly, my colleagues and I engage in a "retreat" at the end of each term, to discuss our insight on our courses and the MDS program as a whole.

Realizing one's own struggles is also critical for self-improvement. For now, one thing I struggle with are student names. I feel embarrassed to use names because I'm sure to make mistakes, but calling students by their name is important because it shows that the instructor cares. I already review class lists, but have been stepping outside of my comfort zone by no longer avoiding using names. Another thing I struggle with is writing in an orderly fashion on the whiteboard. I use the whiteboard for spontaneity / responsive teaching, which means I don't know how I'll ultimately be using the board throughout the class. I end up running out of space, and end up using the board in a non-linear fashion, which can sometimes be confusing. For now, I intend to remain mindful of this and keep practicing.

## Training Philosophy

<!-- must provide evidence for ability to work collaboratively as well as independently, and to supervise the work of others -->

**speach-to-text while doing housework -- needs cleaning, will sound weird**

The groups that I have supervised before include teaching assistants and colleagues with regard with regards to the development and delivery of course material, and students with regards to performing in Capstone project in MDS. Regardless of which group I'm leading, I believe an effective leadership role defining everyone's roles and expectations, and their amount of time commitment; creating an empowering work culture for all group members; and defining success. 

Making everyone's rolls clear is the beginning step in defining a framework for which to operate in. It allows everyone to respect each other's time and boundaries, that there are no surprises when there are interactions between the group. For example, while leading the redevelopment team for DSCI 561 last Summer, are graduate assistant that we hired for the role had her expectations laid out by the hiring conditions, I reiterated them in our kickoff meeting. As for the other colleagues who volunteered their time to take part in this Redevelopment I asked then about how much they would like to contribute to this project and how, well as how much time they would like to invest in the project and how often we should reach out to them in terms of communication. This gave me and others the knowledge of how often we should engage with the other teammates as well as to what extent. Another example is the MDS Capstone project. During our kickoff meeting the students and the partner, I begin by outlining the roles of myself, vince, partner organization. This for example gives the partner organization the knowledge that they are not expected to treat the students as if their employees. It also informed students about who they should go go to talk to for what and how often.

Another important aspect of Define the expectations is defining delegation levels. Longest same line this provides an opportunity for subordinates to learn from me. Example I like to give my teaching assistants the opportunity to teach up to one lecture four Courts that i t. This allows them the opportunity to develop skills that I possess and they do not necessarily, delegation is also a win for me, because it frees up a little bit of my time that I can then spend towards other meaning for activities, ultimately doing more by doing less. When delegating it's also important to let the delegate know how much power they have in decision-making for example are they able to make decisions on their own without consulting me or do I only want them to collects data so that I can make the decision more easily. Going back to the example of the 561 develop the graduate assistant that we hired, I gave her the opportunity to come up with ideas and passing by me before then issuing then what's the requirements to the structure of the knob design in questions, but when it came to deciding how to allocate marks I told her that I would be almost hands off because she has the experience having greatest lab assignments in the past, if anything she would have known better than me. Another example is during Capstone I allow the students who designed their meeting agenda with me. The difficult thing about delegation is you have to give up power in a sentence, because unless you let go of things that you would like to do because you think you know what that last. But I'm letting go you give the delegates the opportunity to grow and learn by stretching their usual boundaries. 

When it comes to the actual nature of the interactions between group members and myself, I believe it's important to empower all group members to feel that they can make an impact. This means respecting each team member as an equally valuable contributor. We should they be viewed as equally valuable but they should be viewed as equal to myself,. By respecting the group and interacting with them as if they are equals this empowers them to take responsibility and ownership over the project and encourages them to express their ideas. It's also important to be careful about how you respond to other people's ideas or questions. It means considering all viewpoints as being good points or equally valuable even if they might seem or even if to me they might obviously be wrong or have an obvious answer. I also like to allow for a culture that safe for descent, which means if somebody disagrees with what I or someone else has to say they should feel safe to be able to express their viewpoint. Ultimately it's cheating this is really about talking to the group as if they're equals and being humble yourself and showing that you are just an ordinary human being like they are. Creating a culture of respect also involves doing things such as respecting people's time and allowing for the opportunity four teammates to meet with me electronically or in person if appropriate whatever they choose. It means not including people in meetings if they are not if their role is not relevant to the meeting. Ultimately it involves being genuine the genuine human being who also has gaps in my skill-set it's important to recognize that ethan subordinates have a different set of skills than the leader does and by treating everyone as equal it gives those unique skill-set city to come about and diverse skill-set in order to create an outcome that is ultimately much better than what the leader could have produced on their own even if given ample time to complete the project. 

Note to self: I've been discussing group work in general including talking to colleagues, I really should just be focussing on subordinate group because that's what training is 

When it comes to the actual learning that my subordinates do jurang be group work call Ma it's important to provided input both verbally and has written feedback. This involves taking the time to write detailed notes as to where they can improve or where they are doing where are they are exceeding expectations already. An example of this is my 561 feedback on Tom's proposed lab assignment, as well as detailed feedback on students capstone reports. It might feel time-consuming while but this is how they are actually going to learn. Another example is when one of my Tas delivers a guest lecture, I like to go for a walk with them outdoor and allow them to tell me how they think the lecture went. I mostly let them do the talking as was inspired by the instructional skills workshop at UBC, but I will also share my own insights and experiences based on what they share insights.

As in teaching i'm also always looking for ways to improve my leadership in training skills. This involves knowledge of where one's weaknesses are. for me, as I learned from last year's Capstone project, I need to be more mindful of group dynamics. Even if things between me and each team member or student is fine the relay between other team members might not be. This year I'll be meeting with each student individually to see how things are going. Play this will solve the problem.

I like to give my TA's the opportunity to deliver a guest lecture. I'll guide them beforehand, and have a "debrief" session, usually a walk outside (inspired from ISW).









### clarity w roles

- Making clear everyone's role in a team project (example: 561 project, capstone projects)
- and getting a sense of the amount of time/involvement each person will be contributing.
- Delegation levels, and being open to letting go (sometimes it's difficult because we want to take ownership)
	- Also, I believe that we don't delegate enough. As a result, we end up sacrificing valuable time where instead we could be really moving the needle in our program.

### culture safe for dissent and cmmunication and respect

- Respecting people's time: giving subordinates the option of meeting electronically if they choose.
- I try to be genuine so that they can see that I'm also a human that makes mistakes and has gaps in my skillset, and lead a regular life outside of UBC. I think this also helps develop a stream of open communication for questions, concerns, and how things are going. Creating a culture that's safe for dissent, because my subordinates have skills, knowledge, and a viewpoint that I don't have, and from which I can learn from them.

### my input: delegation and feedback


- Feedback: taking the time to provide feedback for one's work. I believe this shows respect for the other person, that they are worth my time, and provides an impetus for them to improve. Example: 561 labs 3 and 4 with Tom; detailed feedback on pieces of writing submitted by students (capstone).

- One thing I need to improve upon for this coming capstone, as reflected in my evaluations, is to be more mindful of group dynamics. Even if things between me and each team member/student are fine, relationships between other team members/students might not be. This year, I'll be meeting with each student individually to see how things are going.

