--- 
title: "Application for a Tenure-Track Instructor Position in Statistics at UBC"
author: "Vincenzo Coia"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
geometry: 
- margin=2.0cm
linestretch: 1.5
biblio-style: apalike
link-citations: yes
colorlinks: yes
github-repo: vincenzocoia/ubc-stat-EL-application
description: "Job #35876"
---

# Cover Letter

Dear members of the search committee,

I am writing to enthusiastically apply for a tenure-track instructor position in Statistics ([Job #35876](https://www.stat.ubc.ca/three-tenure-track-instructor-positions-statistics-35876)). Ever since joining the department of Statistics full time in early 2017, largely to advance the Master of Data Science (MDS) program at UBC, I've come to realize just how ideal of a fit the educational leadership stream is for me. My aim with this application is to indicate why this is so, as well as why the department and UBC (and external to UBC!) would benefit by promoting me to the educational leadership (EL) stream. An electronic version of this application can be found at [coia-ubc-application.netlify.com](https://coia-ubc-application.netlify.com/).

Next to this cover letter, you'll first encounter a detailed Curriculum Vitae, where I list my career accomplishments such as the courses I've been involved with and my industry experience. This background has provided me with the necessary data science skills for the EL stream at UBC Statistics: ample use of advanced R and modern tools such as the tidyverse and tidymodels, including a working knowledge of python; other computational tools such as bash scripting, continuous integration, web hosting, and authoring tools such as various markdown flavours and LaTeX; data visualization skills through `ggplot2`, R `shiny`, `plotly`, and others; data formats such as csv, json, and xml; version control through git and collaboration through GitHub; and an advanced knowledge of Statistics, especially when it comes to the practicalities and the "why" of Statistics. I also have the leadership and teaching skills required to keep Data Science education thriving at UBC, as well as the beginnings of contributions (and promises for more) that I believe satisfy the definition of EL. 

I hope these skills speak for themselves throughout this application, in the three statements that follow the CV:

- The "[Statement of vision for education in statistics and data science]" describes my take on Statistics for Data Science. There, I describe the importance and meaning of taking a "problem-first" approach, instead of the "framework-first" approach that should be reserved for Statistical Science. You'll also find my plans for EL, such as a [book](https://interpreting-regression.netlify.com/) and [software](https://github.com/vincenzocoia/distplyr/) I'm writing.
- The "[Statement of teaching and training philosophy]" describes my take on teaching in general, along with how I go about leading groups. There, you can find a discussion of things such as learning objectives being a "true north" when developing a course, and allowing for some spontaneity while teaching, as well as how I lead a group using clarity and equality.
- The "[Diversity Statement]" explains my sensitivity to discrimination, and how simple things such as having pride in who I am, along with calling out discrimination, can promote an inclusive and diverse culture. You just might also find stories about discrimination that I myself have experienced.

I'm applying for the EL position because I want to take my current position one step further, where I can have a bigger impact on Data Science in general. Also, the allure of developing a new Minor program in Data Science is a new and exciting challenge that I can make valuable contributions to, because I know this program is going to be world-class. 

I do admit, however, that I would be torn to leave MDS, because I'm invested in the many projects that are ongoing. But, I imagine maintaining a connection between MDS and the Minor program (as well as STAT 545A/547M, which I've been teaching since 2017), whereby all entities grow together through collaboration and discussions, ensuring that we support each other and provide a service to the community in our own unique ways. I will have been involved in all three data science entities at UBC, so am energized to lead collaboration efforts.

I'd like to reassure you that, although I've only ever officially taught _graduate_ level courses as opposed to undergraduate, I expect the transition to be smooth. Courses in the MDS program are structured like undergraduate courses, and it's not unusual for content to also be at the undergraduate level. Also, I've been involved in the teaching teams of many undergraduate courses as a teaching assistant (TA).

Here are a few links to examples of teaching material that I've created. Note that I don't see any of these as being "finished", but rather a work-in-progress.

- For STAT 545A/547M (Exploratory Data Analysis), I made the [lecture notes](https://stat545guidebook.netlify.com/) and [course website](https://stat545.stat.ubc.ca/) publicly available. Less relevant are Lectures 11+, taught by Dr. Firas Moosvi, and Lecture 6, a guest lecture taught by my TA, Victor Yuan.
- For DSCI 551 (Probability for Data Science), I wrote most of the [lecture notes](https://ubc-mds.github.io/DSCI_551_stat-prob-dsci/lectures/) by using Dr. Mike Gelbart's notes from the previous year as scaffolding.
- You can find the [DSCI 531 notes here](https://ubc-mds.github.io/DSCI_531_viz-1/) from the 2018/19 academic year, reflecting an older way I would structure course material.
- You can find the [DSCI 562 notes here](https://ubc-mds.github.io/DSCI_562_regr-2/) from last year. This still needs lots of help, but the foundations are there.
- I'm writing an open-source book on regression analysis for Data Science, called [Interpreting Regression](https://interpreting-regression.netlify.com/). It's in its early stages.

You may also find it useful to obtain a list of MDS courses that I would feel comfortable (or uncomfortable) teaching. You can find that list in the [Course Involvement] section of my CV.

I'd be remiss to forego mentioning just why this position fits my career goals. I've identified four pillars of an ideal career. It took me a while to figure out that the EL position nicely satisfies all four, which is why I didn't apply for the position back in 2017. These pillars are, in order of culmination:

1. __Application__: addressing real problems with data science. I will continue to actively seek to "sharpen the saw" by putting myself in front of real problems, as I mention in the [Educational Leadership] of my vision for education in Statistics.
2. __Research__: discovering better ways to do data science. To me, this means reframing Statistics from a problem-first approach, and bringing useful yet under-utilized tools to the table. You can read about this in the [Statistics for Data Science] section in my vision for education in Statistics. 
3. __Development__: turning new research into programs and tools, which are ideally accessible to the public. To me, this means developing products under the umbrella of EL, such as books and software. You can read about this in the [Educational Leadership] section in my vision for education in Statistics.
4. __Teaching__: spreading data literacy and enthusiasm to the public. Teaching university courses is a dream come true for me, and so is being a leader by training in a group setting. You can read about this in my [Statement of teaching and training philosophy].

Here are the names of three references who will submit letters by the end of December 13, 2019:

1. Dr. Tiffany Timbers, UBC (current supervisor)
2. Dr. Michael Gelbart, UBC (current supervisor)
3. Dr. Harry Joe, UBC (PhD supervisor)

I am eager to begin the position on the indicated July 1, 2020 start date, but am ultimately flexible. I'm looking forward to talking more about my fit in this EL position in person.

Sincerely yours,

Vincenzo Coia, PhD

https://vincenzocoia.com/
